# Generated by Django 4.2.5 on 2023-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_mark_delete_cars_car_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
