# Generated by Django 4.2.5 on 2023-10-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_color_alter_car_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.year'),
            preserve_default=False,
        ),
    ]
