# Generated by Django 4.2.5 on 2023-10-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_year_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.fuel'),
            preserve_default=False,
        ),
    ]
