# Generated by Django 4.2.5 on 2024-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
