# Generated by Django 4.2.5 on 2024-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_riflespagevideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiflesPagePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='rifles_page_photos')),
                ('price', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RiflesPageVideos',
        ),
    ]
