# Generated by Django 4.2.5 on 2024-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_riflespagephotos_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiflesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='rifles_page')),
                ('price', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='RiflesPagePhotos',
        ),
    ]
