# Generated by Django 4.2.5 on 2024-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_riflespage_delete_riflespagephotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vidguk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vidguk', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
