# Generated by Django 4.2.5 on 2024-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_vidguk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidguk',
            name='vidguk',
            field=models.CharField(max_length=1000),
        ),
    ]
