# Generated by Django 4.2.5 on 2024-02-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_feedback_delete_vidguk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_name',
            new_name='feedback_text',
        ),
    ]
