# Generated by Django 4.2.5 on 2024-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_feedback_delete_vidguk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SniperRiflesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='sniper_rifles_page')),
                ('price', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
