# Generated by Django 4.2.5 on 2024-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_sniperriflespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riflespage',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='riflespage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sniperriflespage',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sniperriflespage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
